name: CI

on:
    push:
    schedule:
        - cron: "0 2 * * 1" # The task runs at 2 a.m. every Monday.

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 6
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.9", "3.10", "3.11", "3.12", "3.x"]
        name: Python ${{ matrix.python-version }} ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip pytest

            - name: Test with pytest
              env:
                  PYTHONPATH: src
              run: |
                  python -m pytest tests/ -p no:warnings -vv
